id: P74362109
initial_creation_type: input
source_metadata:
  title: Fourteenth Dalai Lama Series
  language: es
  description: 'Texts by and about His Holiness the 14th Dalai Lama, Tenzin Gyatso
    (bstan ''dzin rgya mtsho, b. 1935):'
  volume:
    2d80809a2ad74abc8e2a2237e4ea5e2e:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Aspiration Prayers
    e7fc9773069f4b34aaa15ba0773718fc:
      title: The Prayer of the Words of Truth
      parent: Aspiration Prayers
    2b4936c2a4c7478ba7e1f61ff49d7105:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Aspiration Prayers
    02cc5915d159430a9628cac63694bc77:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Aspiration Prayers
    d9fd42b088fc4195a4680bdb87c7c506:
      title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the
        Enlightened Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton
        Lerab Lingpa'
      parent: Aspiration Prayers
    683afa8cc7be40818f938a1fe2829a41:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Guru Rinpoche Prayers
    46758b0991034796b3c13c4f3c8a3fd1:
      title: A Letter to the Fourteenth Dalai Lama, Supreme Victorious Guru of the
        Beings of the Three Realms
      parent: Letters
    e5227fd5f63e4d2ebc113928fb5d9d7d:
      title: A Prayer to Kindle the Three Faiths, Addressed to the Seventeen Great
        Paṇḍitas of Glorious Nālandā
      parent: Lineage Prayers
    4f3f4c9fed824138b4709acf1c57aa7e:
      title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind
        Kīla Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Lineage Prayers
    f7ec5edb02064e3c8d1031dec5681bd1:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    2a1cfcb91ada4e26a6ddce15b821e0ba:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    0c595ee8221542808df44959d1ca08a7:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    cab18388dc5e4fa18fed152caca6d45e:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    a6d8bdb6618a4f36a313cee6363ecf7f:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    d84a14b89b7f4ae2982c8ac2cdaa0541:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      parent: Long Life Prayers
    48c4b00218244830b92c5abca7a5593a:
      title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His
        Holiness the Dalai Lama'
      parent: Long Life Prayers
    3603f5f4f9d24f95b254b7908cb31262:
      title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life
        of His Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One
        by Jamyang Khyentse Chökyi Lodrö'
      parent: Long Life Prayers
    ed8a2c41484748d8a9348284b2a77f03:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    29c89a632f2d412b97470e5579118968:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    9a8e5dbd7cf84b20a7b88f04469179d2:
      title: Verses of Homage
      parent: Praise
    65086c8b10bf4692be5c804fba0c494e:
      title: Prayer for the Fulfilment of Aspirations
      parent: Prayers
    41609f67109046f689d2782ac01df622:
      title: Prayer to His Holiness the Dalai Lama
      parent: Prayers
    c1bca3de928448b1b51354fc9f0b54e3:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
    6b1162a50bc6454791542271b98cbe8b:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Vajrakīla
created_at: '2022-02-28T23:17:49.859623'
last_modified_at: '2022-02-28T23:17:49.859626'
